name: Bug Report
description: Report a bug in dechromium
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Create a profile with ...
        2. Start the browser ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include error messages or tracebacks if applicable.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: dechromium version
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: chromium_version
    attributes:
      label: Chromium version
      placeholder: "145.0.7632.116"

  - type: input
    id: python_version
    attributes:
      label: Python version
      placeholder: "3.12"

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "Ubuntu 24.04"
